package: auto_delete 
version: '1.0.3'
author: 'Alexander Walther' 
supportpage: https://github.com/alexplusde/auto_delete 


requires:                       
    php:
        version: '>=8.4,<9'
    redaxo: '^5.18.3'
    packages:
        yform: ">=4,<6"
        cronjob: "^2.8"

page:
    title: translate:auto_delete_title
    prio: 100
    icon: rex-icon fa-gear
    hidden: true
