package: auto_delete 
version: '2.0.0-dev-2025-07-12'
author: 'Alexander Walther' 
supportpage: https://github.com/alexplusde/auto_delete 


requires:                       
    php:
        version: '>=8.3,<9'
    redaxo: '^5.18.3'
    packages:
        yform: ">=4,<6"
        cronjob: "^2.8"
