package: auto_delete 
version: '1.0.2'
author: 'Alexander Walther' 
supportpage: https://github.com/alexplusde/auto_delete 


requires:                       
    php:
        version: '>7.3,<9'
    redaxo: ^5.13
    packages:
        yform: "^4"
        cronjob: "^2.8"

page:
    title: translate:auto_delete_title
    prio: 100
    icon: rex-icon fa-gear
    hidden: true
